import type { Settings, RolePoints, Language, Role } from './types';

export const ADMIN_PASSWORD = '22112211L@@';

export const DEFAULT_SETTINGS: Settings = {
  theme: 'wooden',
  sound: true,
  vibration: true,
  music: true,
  language: 'en',
};

export const DEFAULT_ROLE_POINTS: RolePoints = {
  King: 1000,
  Minister: 800,
  Soldier: 500,
  Thief: 0,
  Laundry: 100,
  Cleaner: 50,
};

export const SOUNDS = {
  click: 'https://cdn.pixabay.com/audio/2022/03/15/audio_5131422b54.mp3',
  backgroundMusic: 'https://cdn.pixabay.com/audio/2022/08/03/audio_5852865d53.mp3',
  reveal: 'https://cdn.pixabay.com/audio/2021/08/04/audio_12b0c342f5.mp3',
  win: 'https://cdn.pixabay.com/audio/2022/11/17/audio_88c72a652c.mp3',
  lose: 'https://cdn.pixabay.com/audio/2022/03/10/audio_c38aede199.mp3',
};

export const ROLE_ICONS: Record<Role, string> = {
  King: '👑',
  Minister: '📜',
  Soldier: '🛡️',
  Thief: '🎭',
  Laundry: '🧺',
  Cleaner: '🧹',
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    'Find the Thief': 'Find the Thief',
    'Play': 'Play',
    'Settings': 'Settings',
    'Update Suggests': 'Update Suggests',
    'Bug Report': 'Bug Report',
    'Theme': 'Theme',
    'Wooden': 'Wooden',
    'Modern Futuristic': 'Modern Futuristic',
    'Minecraft': 'Minecraft',
    'GTA 5': 'GTA 5',
    'Sound': 'Sound',
    'Vibration': 'Vibration',
    'Music': 'Music',
    'Back': 'Back',
    'Send': 'Send',
    'Enter Admin Password': 'Enter Admin Password',
    'You are not admin, can’t see suggests.': 'You are not admin, can’t see suggests.',
    'No suggestions yet.': 'No suggestions yet.',
    'Suggestions': 'Suggestions',
    'Write your suggestion here...': 'Write your suggestion here...',
    'View Suggestions': 'View Suggestions',
    'Bug Reports': 'Bug Reports',
    'Describe the bug...': 'Describe the bug...',
    'Upload Screenshot (Optional)': 'Upload Screenshot (Optional)',
    'No bug reports yet.': 'No bug reports yet.',
    'Enter Players': 'Enter Players',
    'Number of Players': 'Number of Players',
    'Player Name': 'Player Name',
    'Role Points': 'Role Points',
    'Total Rounds': 'Total Rounds',
    'Start Game': 'Start Game',
    'Select Paper': 'Select Paper',
    'Your Role is...': 'Your Role is...',
    'OK': 'OK',
    'Reveal Roles': 'Reveal Roles',
    'All roles revealed!': 'All roles revealed!',
    'Start Round': 'Start Round',
    'Round': 'Round',
    'of': 'of',
    'King': 'King',
    'Minister': 'Minister',
    'Soldier': 'Soldier',
    'Thief': 'Thief',
    'commands': 'commands',
    'Find the Thief!': 'Find the Thief!',
    'Guess the Thief': 'Guess the Thief',
    'Correct Guess!': 'Correct Guess!',
    'Wrong Guess!': 'Wrong Guess!',
    'was the Thief.': 'was the Thief.',
    'Next Round': 'Next Round',
    'Show Results': 'Show Results',
    'Game Over': 'Game Over',
    'Final Scores': 'Final Scores',
    'Restart': 'Restart',
    'Exit': 'Exit',
    'Pause': 'Pause',
    'Resume': 'Resume',
    'Game Paused': 'Game Paused',
    'Points': 'Points',
    'Lost': 'Lost',
  },
  ur: {
    'Find the Thief': 'چور کو تلاش کریں',
    'Play': 'کھیلیں',
    'Settings': 'ترتیبات',
    'Update Suggests': 'تجاویز',
    'Bug Report': 'بگ رپورٹ',
    'Theme': 'تھیم',
    'Wooden': 'لکڑی',
    'Modern Futuristic': 'جدید مستقبل',
    'Minecraft': 'مائن کرافٹ',
    'GTA 5': 'جی ٹی اے 5',
    'Sound': 'آواز',
    'Vibration': 'تھرتھراہٹ',
    'Music': 'موسیقی',
    'Back': 'واپس',
    'Send': 'بھیجیں',
    'Enter Admin Password': 'ایڈمن پاس ورڈ درج کریں',
    'You are not admin, can’t see suggests.': 'آپ ایڈمن نہیں ہیں، تجاویز نہیں دیکھ سکتے۔',
    'No suggestions yet.': 'ابھی تک کوئی تجاویز نہیں ہیں۔',
    'Suggestions': 'تجاویز',
    'Write your suggestion here...': 'اپنی تجویز یہاں لکھیں...',
    'View Suggestions': 'تجاویز دیکھیں',
    'Bug Reports': 'بگ رپورٹس',
    'Describe the bug...': 'بگ کی وضاحت کریں...',
    'Upload Screenshot (Optional)': 'اسکرین شاٹ اپ لوڈ کریں (اختیاری)',
    'No bug reports yet.': 'ابھی تک کوئی بگ رپورٹ نہیں ہے۔',
    'Enter Players': 'کھلاڑی داخل کریں',
    'Number of Players': 'کھلاڑیوں کی تعداد',
    'Player Name': 'کھلاڑی کا نام',
    'Role Points': 'کردار کے پوائنٹس',
    'Total Rounds': 'کل راؤنڈز',
    'Start Game': 'کھیل شروع کریں',
    'Select Paper': 'کاغذ منتخب کریں',
    'Your Role is...': 'آپ کا کردار ہے...',
    'OK': 'ٹھیک ہے',
    'Reveal Roles': 'کردار ظاہر کریں',
    'All roles revealed!': 'تمام کردار ظاہر ہو گئے!',
    'Start Round': 'راؤنڈ شروع کریں',
    'Round': 'راؤنڈ',
    'of': 'کا',
    'King': 'بادشاہ',
    'Minister': 'وزیر',
    'Soldier': 'سپاہی',
    'Thief': 'چور',
    'commands': 'حکم دیتا ہے',
    'Find the Thief!': 'چور کو تلاش کرو!',
    'Guess the Thief': 'چور کا اندازہ لگائیں',
    'Correct Guess!': 'صحیح اندازہ!',
    'Wrong Guess!': 'غلط اندازہ!',
    'was the Thief.': 'چور تھا۔',
    'Next Round': 'اگلا راؤنڈ',
    'Show Results': 'نتائج دکھائیں',
    'Game Over': 'کھیل ختم',
    'Final Scores': 'حتمی اسکور',
    'Restart': 'دوبارہ شروع کریں',
    'Exit': 'باہر نکلیں',
    'Pause': 'روکیں',
    'Resume': 'دوبارہ شروع',
    'Game Paused': 'کھیل روک دیا گیا',
    'Points': 'پوائنٹس',
    'Lost': 'ہار گئے',
  },
  hi: {
    'Find the Thief': 'चोर को ढूंढो',
    'Play': 'खेलें',
    'Settings': 'सेटिंग्स',
    'Update Suggests': 'सुझाव',
    'Bug Report': 'बग रिपोर्ट',
    'Theme': 'थीम',
    'Wooden': 'लकड़ी',
    'Modern Futuristic': 'आधुनिक भविष्य',
    'Minecraft': 'माइनक्राफ्ट',
    'GTA 5': 'जीटीए 5',
    'Sound': 'ध्वनि',
    'Vibration': 'कंपन',
    'Music': 'संगीत',
    'Back': 'वापस',
    'Send': 'भेजें',
    'Enter Admin Password': 'एडमिन पासवर्ड डालें',
    'You are not admin, can’t see suggests.': 'आप एडमिन नहीं हैं, सुझाव नहीं देख सकते।',
    'No suggestions yet.': 'अभी तक कोई सुझाव नहीं है।',
    'Suggestions': 'सुझाव',
    'Write your suggestion here...': 'अपना सुझाव यहां लिखें...',
    'View Suggestions': 'सुझाव देखें',
    'Bug Reports': 'बग रिपोर्ट',
    'Describe the bug...': 'बग का वर्णन करें...',
    'Upload Screenshot (Optional)': 'स्क्रीनशॉट अपलोड करें (वैकल्पिक)',
    'No bug reports yet.': 'अभी तक कोई बग रिपोर्ट नहीं है।',
    'Enter Players': 'खिलाड़ी दर्ज करें',
    'Number of Players': 'खिलाड़ियों की संख्या',
    'Player Name': 'खिलाड़ी का नाम',
    'Role Points': 'भूमिका अंक',
    'Total Rounds': 'कुल राउंड',
    'Start Game': 'खेल शुरू करें',
    'Select Paper': 'कागज चुनें',
    'Your Role is...': 'आपकी भूमिका है...',
    'OK': 'ठीक है',
    'Reveal Roles': 'भूमिकाएं प्रकट करें',
    'All roles revealed!': 'सभी भूमिकाएं प्रकट हो गईं!',
    'Start Round': 'राउंड शुरू करें',
    'Round': 'राउंड',
    'of': 'का',
    'King': 'राजा',
    'Minister': 'मंत्री',
    'Soldier': 'सैनिक',
    'Thief': 'चोर',
    'commands': 'आदेश देता है',
    'Find the Thief!': 'चोर को ढूंढो!',
    'Guess the Thief': 'चोर का अनुमान लगाएं',
    'Correct Guess!': 'सही अनुमान!',
    'Wrong Guess!': 'गलत अनुमान!',
    'was the Thief.': 'चोर था।',
    'Next Round': 'अगला राउंड',
    'Show Results': 'परिणाम दिखाएं',
    'Game Over': 'खेल खत्म',
    'Final Scores': 'अंतिम स्कोर',
    'Restart': 'पुनः आरंभ करें',
    'Exit': 'बाहर निकलें',
    'Pause': 'रोकें',
    'Resume': 'फिर से शुरू करें',
    'Game Paused': 'खेल रुका हुआ है',
    'Points': 'अंक',
    'Lost': 'हार गए',
  },
  ro: {
    'Find the Thief': 'Chor ko Talash Karein',
    'Play': 'Khelein',
    'Settings': 'Settings',
    'Update Suggests': 'Tajaveez',
    'Bug Report': 'Bug Report',
    'Theme': 'Theme',
    'Wooden': 'Lakri',
    'Modern Futuristic': 'Jadeed Mustaqbil',
    'Minecraft': 'Minecraft',
    'GTA 5': 'GTA 5',
    'Sound': 'Awaz',
    'Vibration': 'Thartharahat',
    'Music': 'Moseeqi',
    'Back': 'Wapis',
    'Send': 'Bhejein',
    'Enter Admin Password': 'Admin Password Darj Karein',
    'You are not admin, can’t see suggests.': 'Aap admin nahi hain, tajaveez nahi dekh sakte.',
    'No suggestions yet.': 'Abhi tak koi tajaveez nahi hain.',
    'Suggestions': 'Tajaveez',
    'Write your suggestion here...': 'Apni tajweez yahan likhein...',
    'View Suggestions': 'Tajaveez Dekhein',
    'Bug Reports': 'Bug Reports',
    'Describe the bug...': 'Bug ki wazahat karein...',
    'Upload Screenshot (Optional)': 'Screenshot Upload Karein (Ikhtiyari)',
    'No bug reports yet.': 'Abhi tak koi bug report nahi hai.',
    'Enter Players': 'Khiladi dakhil karein',
    'Number of Players': 'Khiladiyon ki tadad',
    'Player Name': 'Khiladi ka Naam',
    'Role Points': 'Kirdar ke Points',
    'Total Rounds': 'Kul Rounds',
    'Start Game': 'Khel Shuru Karein',
    'Select Paper': 'Kaghaz Muntakhab Karein',
    'Your Role is...': 'Aap ka kirdar hai...',
    'OK': 'Theek hai',
    'Reveal Roles': 'Kirdar Zahir Karein',
    'All roles revealed!': 'Sab kirdar zahir ho gaye!',
    'Start Round': 'Round Shuru Karein',
    'Round': 'Round',
    'of': 'ka',
    'King': 'Badshah',
    'Minister': 'Wazir',
    'Soldier': 'Sipahi',
    'Thief': 'Chor',
    'commands': 'hukum deta hai',
    'Find the Thief!': 'Chor ko dhoondo!',
    'Guess the Thief': 'Chor ka andaza lagayein',
    'Correct Guess!': 'Sahi andaza!',
    'Wrong Guess!': 'Ghalat andaza!',
    'was the Thief.': 'chor tha.',
    'Next Round': 'Agla Round',
    'Show Results': 'Nataij Dikhayein',
    'Game Over': 'Khel Khatam',
    'Final Scores': 'Aakhri Scores',
    'Restart': 'Dobara Shuru Karein',
    'Exit': 'Bahir Niklein',
    'Pause': 'Rokein',
    'Resume': 'Dobara Shuru',
    'Game Paused': 'Khel roka gaya',
    'Points': 'Points',
    'Haar gaye': 'Haar gaye',
  },
};