import type { Settings, RolePoints, Language, Role } from './types';

export const ADMIN_PASSWORD = '22112211L@@';

export const HINT_COSTS = {
  SMALL: 10,
  NORMAL: 20,
  BIG: 35,
  REAL: 50,
};

export const DEFAULT_SETTINGS: Settings = {
  theme: 'wooden',
  sound: true,
  vibration: true,
  music: true,
  language: 'en',
};

export const DEFAULT_ROLE_POINTS: RolePoints = {
  King: 1000,
  Minister: 800,
  Soldier: 500,
  Thief: 0,
  Laundry: 100,
  Cleaner: 50,
  Chef: 200,
  Gardener: 150,
  Prince: 900,
  Queen: 1200,
};

export const SOUNDS = {
  click: 'https://cdn.pixabay.com/audio/2022/03/15/audio_5131422b54.mp3',
  backgroundMusic: 'https://cdn.pixabay.com/audio/2022/08/03/audio_5852865d53.mp3',
  reveal: 'https://cdn.pixabay.com/audio/2021/08/04/audio_12b0c342f5.mp3',
  win: 'https://cdn.pixabay.com/audio/2022/11/17/audio_88c72a652c.mp3',
  lose: 'https://cdn.pixabay.com/audio/2022/03/10/audio_c38aede199.mp3',
};

export const ROLE_ICONS: Record<Role, string> = {
  King: '👑',
  Minister: '📜',
  Soldier: '🛡️',
  Thief: '🎭',
  Laundry: '🧺',
  Cleaner: '🧹',
  Chef: '👨‍🍳',
  Gardener: '👨‍🌾',
  Prince: '🤴',
  Queen: '👸',
};

export const CORE_ROLES: Role[] = ['King', 'Minister', 'Soldier', 'Thief'];
export const EXTRA_ROLES: Role[] = ['Laundry', 'Cleaner', 'Chef', 'Gardener', 'Prince', 'Queen'];


export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    'Find the Thief': 'Find the Thief',
    'Local Play': 'Local Play',
    'Multiplayer': 'Multiplayer',
    'Settings': 'Settings',
    'Update Suggests': 'Update Suggests',
    'Bug Report': 'Bug Report',
    'Tutorial': 'Tutorial',
    'Theme': 'Theme',
    'Wooden': 'Wooden',
    'Modern Futuristic': 'Modern Futuristic',
    'Minecraft': 'Minecraft',
    'GTA 5': 'GTA 5',
    'Classic': 'Classic',
    'Paper': 'Paper',
    'Real Life': 'Real Life',
    'Sound': 'Sound',
    'Vibration': 'Vibration',
    'Music': 'Music',
    'Back': 'Back',
    'Send': 'Send',
    'Enter Admin Password': 'Enter Admin Password',
    'You are not admin, can’t see suggests.': 'You are not admin, can’t see suggests.',
    'No suggestions yet.': 'No suggestions yet.',
    'Suggestions': 'Suggestions',
    'Write your suggestion here...': 'Write your suggestion here...',
    'View Suggestions': 'View Suggestions',
    'Bug Reports': 'Bug Reports',
    'Describe the bug...': 'Describe the bug...',
    'Upload Screenshot (Optional)': 'Upload Screenshot (Optional)',
    'No bug reports yet.': 'No bug reports yet.',
    'Enter Players': 'Enter Players',
    'Number of Players': 'Number of Players',
    'Player Name': 'Player Name',
    'Role Points': 'Role Points',
    'Total Rounds': 'Total Rounds',
    'Start Game': 'Start Game',
    'Select Paper': 'Select Paper',
    'Your Role is...': 'Your Role is...',
    'OK': 'OK',
    'Reveal Roles': 'Reveal Roles',
    'All roles revealed!': 'All roles revealed!',
    'Start Round': 'Start Round',
    'Round': 'Round',
    'of': 'of',
    'King': 'King',
    'Minister': 'Minister',
    'Soldier': 'Soldier',
    'Thief': 'Thief',
    'Queen': 'Queen',
    'Prince': 'Prince',
    'Chef': 'Chef',
    'Gardener': 'Gardener',
    'commands': 'commands',
    'Find the Thief!': 'Find the Thief!',
    'Guess the Thief': 'Guess the Thief',
    'Correct Guess!': 'Correct Guess!',
    'Wrong Guess!': 'Wrong Guess!',
    'was the Thief.': 'was the Thief.',
    'Next Round': 'Next Round',
    'Show Results': 'Show Results',
    'Game Over': 'Game Over',
    'Final Scores': 'Final Scores',
    'Restart': 'Restart',
    'Exit': 'Exit',
    'Pause': 'Pause',
    'Resume': 'Resume',
    'Game Paused': 'Game Paused',
    'Points': 'Points',
    'Lost': 'Lost',
    'Number of AI Opponents': 'Number of AI Opponents',
    'Your Name': 'Your Name',
    'Minister is thinking...': 'Minister is thinking...',
    'Add Player': 'Add Player',
    'Remove': 'Remove',
    'Human': 'Human',
    'AI': 'AI',
    'Player Names': 'Player Names',
    'Coins': 'Coins',
    'Buy Hint': 'Buy Hint',
    'Hint': 'Hint',
    'is not the Thief.': 'is not the Thief.',
    'Not enough coins!': 'Not enough coins!',
    'You earned': 'You earned',
    'coins!': 'coins!',
    'No coins are awarded in 2-player human games.': 'No coins are awarded in 2-player human games.',
    'Username': 'Username',
    'Continue': 'Continue',
    'Enter your username': 'Enter your username',
    'Create Game': 'Create Game',
    'Join Game': 'Join Game',
    'Enter Game ID': 'Enter Game ID',
    'Game ID': 'Game ID',
    'Copy': 'Copy',
    'Copied!': 'Copied!',
    'Waiting for players...': 'Waiting for players...',
    'Leave Lobby': 'Leave Lobby',
    'Players': 'Players',
    'Game not found.': 'Game not found.',
    'Lobby is full.': 'Lobby is full.',
    'Game has already started.': 'Game has already started.',
    'Small Hint': 'Small Hint',
    'Normal Hint': 'Normal Hint',
    'Big Hint': 'Big Hint',
    'Real Answer': 'Real Answer',
    'Reveal one innocent player.': 'Reveal one innocent player.',
    'Reveal two innocent players.': 'Reveal two innocent players.',
    'Reveal three innocent players.': 'Reveal three innocent players.',
    'Reveal the Thief!': 'Reveal the Thief!',
    'is the Thief!': 'is the Thief!',
    'and': 'and',
    'are not the Thief.': 'are not the Thief.',
    'Not enough players for this hint.': 'Not enough players for this hint.',
    'Previous': 'Previous',
    'Next': 'Next',
    'Welcome to Find the Thief!': 'Welcome to Find the Thief!',
    'The goal is simple: The Minister must find and identify the Thief to win the round.': 'The goal is simple: The Minister must find and identify the Thief to win the round.',
    'Meet the Key Players': 'Meet the Key Players',
    'King_Desc': 'The ruler! Their score is safe.',
    'Minister_Desc': 'The detective! They must guess who the Thief is.',
    'Soldier_Desc': 'The guard! They have a role but don\'t act in the guessing phase.',
    'Thief_Desc': 'The culprit! They win if the Minister guesses incorrectly.',
    'A Round of Play': 'A Round of Play',
    'Round_Desc': '1. Everyone gets a secret role. 2. The King commands the Minister to find the Thief. 3. The Minister makes a guess. 4. Roles are revealed, and points are awarded.',
    'Winning & Losing': 'Winning & Losing',
    'Scoring_Desc': 'If the Minister guesses correctly, they get points. If they are wrong, the Thief gets the points, and the Minister\'s score for the round is zero! The player with the most points after all rounds wins.',
    "You're Ready!": "You're Ready!",
    'Good_Luck': 'That\'s all you need to know. Now go out there and find that thief! Good luck!',
  },
  ur: {
    'Find the Thief': 'چور کو تلاش کریں',
    'Local Play': 'مقامی کھیل',
    'Multiplayer': 'ملٹی پلیئر',
    'Settings': 'ترتیبات',
    'Update Suggests': 'تجاویز',
    'Bug Report': 'بگ رپورٹ',
    'Tutorial': 'ٹریننگ',
    'Theme': 'تھیم',
    'Wooden': 'لکڑی',
    'Modern Futuristic': 'جدید مستقبل',
    'Minecraft': 'مائن کرافٹ',
    'GTA 5': 'جی ٹی اے 5',
    'Classic': 'کلاسیک',
    'Paper': 'کاغذی',
    'Real Life': 'حقیقی زندگی',
    'Sound': 'آواز',
    'Vibration': 'تھرتھراہٹ',
    'Music': 'موسیقی',
    'Back': 'واپس',
    'Send': 'بھیجیں',
    'Enter Admin Password': 'ایڈمن پاس ورڈ درج کریں',
    'You are not admin, can’t see suggests.': 'آپ ایڈمن نہیں ہیں، تجاویز نہیں دیکھ سکتے۔',
    'No suggestions yet.': 'ابھی تک کوئی تجاویز نہیں ہیں۔',
    'Suggestions': 'تجاویز',
    'Write your suggestion here...': 'اپنی تجویز یہاں لکھیں...',
    'View Suggestions': 'تجاویز دیکھیں',
    'Bug Reports': 'بگ رپورٹس',
    'Describe the bug...': 'بگ کی وضاحت کریں...',
    'Upload Screenshot (Optional)': 'اسکرین شاٹ اپ لوڈ کریں (اختیاری)',
    'No bug reports yet.': 'ابھی تک کوئی بگ رپورٹ نہیں ہے۔',
    'Enter Players': 'کھلاڑی داخل کریں',
    'Number of Players': 'کھلاڑیوں کی تعداد',
    'Player Name': 'کھلاڑی کا نام',
    'Role Points': 'کردار کے پوائنٹس',
    'Total Rounds': 'کل راؤنڈز',
    'Start Game': 'کھیل شروع کریں',
    'Select Paper': 'کاغذ منتخب کریں',
    'Your Role is...': 'آپ کا کردار ہے...',
    'OK': 'ٹھیک ہے',
    'Reveal Roles': 'کردار ظاہر کریں',
    'All roles revealed!': 'تمام کردار ظاہر ہو گئے!',
    'Start Round': 'راؤنڈ شروع کریں',
    'Round': 'راؤنڈ',
    'of': 'کا',
    'King': 'بادشاہ',
    'Minister': 'وزیر',
    'Soldier': 'سپاہی',
    'Thief': 'چور',
    'Queen': 'ملکہ',
    'Prince': 'شہزادہ',
    'Chef': 'باورچی',
    'Gardener': 'مالی',
    'commands': 'حکم دیتا ہے',
    'Find the Thief!': 'چور کو تلاش کرو!',
    'Guess the Thief': 'چور کا اندازہ لگائیں',
    'Correct Guess!': 'صحیح اندازہ!',
    'Wrong Guess!': 'غلط اندازہ!',
    'was the Thief.': 'چور تھا۔',
    'Next Round': 'اگلا راؤنڈ',
    'Show Results': 'نتائج دکھائیں',
    'Game Over': 'کھیل ختم',
    'Final Scores': 'حتمی اسکور',
    'Restart': 'دوبارہ شروع کریں',
    'Exit': 'باہر نکلیں',
    'Pause': 'روکیں',
    'Resume': 'دوبارہ شروع',
    'Game Paused': 'کھیل روک دیا گیا',
    'Points': 'پوائنٹس',
    'Lost': 'ہار گئے',
    'Number of AI Opponents': 'AI مخالفین کی تعداد',
    'Your Name': 'آپ کا نام',
    'Minister is thinking...': 'وزیر سوچ رہا ہے...',
    'Add Player': 'کھلاڑی شامل کریں',
    'Remove': 'ہٹائیں',
    'Human': 'انسان',
    'AI': 'اے آئی',
    'Player Names': 'کھلاڑیوں کے نام',
    'Coins': 'سکے',
    'Buy Hint': 'اشارہ خریدیں',
    'Hint': 'اشارہ',
    'is not the Thief.': 'چور نہیں ہے۔',
    'Not enough coins!': 'کافی سکے نہیں ہیں!',
    'You earned': 'آپ نے کمائے',
    'coins!': 'سکے!',
    'No coins are awarded in 2-player human games.': '2 انسانی کھلاڑیوں والے کھیلوں میں کوئی سکے نہیں دیے جاتے۔',
    'Username': 'صارف کا نام',
    'Continue': 'جاری رکھیں',
    'Enter your username': 'اپنا صارف نام درج کریں',
    'Create Game': 'گیم بنائیں',
    'Join Game': 'گیم میں شامل ہوں',
    'Enter Game ID': 'گیم آئی ڈی درج کریں',
    'Game ID': 'گیم آئی ڈی',
    'Copy': 'کاپی',
    'Copied!': 'کاپی ہو گیا!',
    'Waiting for players...': 'کھلاڑیوں کا انتظار ہے...',
    'Leave Lobby': 'لابی چھوڑ دیں',
    'Players': 'کھلاڑی',
    'Game not found.': 'گیم نہیں ملا۔',
    'Lobby is full.': 'لابی بھری ہوئی ہے۔',
    'Game has already started.': 'کھیل پہلے ہی شروع ہو چکا ہے۔',
    'Small Hint': 'چھوٹا اشارہ',
    'Normal Hint': 'عام اشارہ',
    'Big Hint': 'بڑا اشارہ',
    'Real Answer': 'اصل جواب',
    'Reveal one innocent player.': 'ایک معصوم کھلاڑی کو ظاہر کریں۔',
    'Reveal two innocent players.': 'دو معصوم کھلاڑیوں کو ظاہر کریں۔',
    'Reveal three innocent players.': 'تین معصوم کھلاڑیوں کو ظاہر کریں۔',
    'Reveal the Thief!': 'چور کو ظاہر کرو!',
    'is the Thief!': 'چور ہے!',
    'and': 'اور',
    'are not the Thief.': 'چور نہیں ہیں۔',
    'Not enough players for this hint.': 'اس اشارے کے لیے کافی کھلاڑی نہیں ہیں۔',
    'Previous': 'پچھلا',
    'Next': 'اگلا',
    'Welcome to Find the Thief!': 'چور کو تلاش کریں میں خوش آمدید!',
    'The goal is simple: The Minister must find and identify the Thief to win the round.': 'مقصد آسان ہے: وزیر کو راؤنڈ جیتنے کے لیے چور کو ڈھونڈنا اور شناخت کرنا ہوگا۔',
    'Meet the Key Players': 'اہم کھلاڑیوں سے ملیں',
    'King_Desc': 'حکمران! ان کا اسکور محفوظ ہے۔',
    'Minister_Desc': 'جاسوس! انہیں اندازہ لگانا ہوگا کہ چور کون ہے۔',
    'Soldier_Desc': 'محافظ! ان کا ایک کردار ہے لیکن اندازہ لگانے کے مرحلے میں کوئی عمل نہیں۔',
    'Thief_Desc': 'مجرم! اگر وزیر غلط اندازہ لگاتا ہے تو وہ جیت جاتے ہیں۔',
    'A Round of Play': 'کھیل کا ایک راؤنڈ',
    'Round_Desc': '۱. ہر ایک کو ایک خفیہ کردار ملتا ہے۔ ۲. بادشاہ وزیر کو چور کو ڈھونڈنے کا حکم دیتا ہے۔ ۳. وزیر ایک اندازہ لگاتا ہے۔ ۴. کردار ظاہر کیے جاتے ہیں، اور پوائنٹس دیے جاتے ہیں۔',
    'Winning & Losing': 'جیتنا اور ہارنا',
    'Scoring_Desc': 'اگر وزیر صحیح اندازہ لگاتا ہے، تو اسے پوائنٹس ملتے ہیں۔ اگر وہ غلط ہے، تو چور کو پوائنٹس ملتے ہیں، اور وزیر کا اس راؤنڈ کا اسکور صفر ہوجاتا ہے! تمام راؤنڈز کے بعد سب سے زیادہ پوائنٹس والا کھلاڑی جیتتا ہے۔',
    "You're Ready!": 'آپ تیار ہیں!',
    'Good_Luck': 'آپ کو بس اتنا ہی جاننے کی ضرورت ہے۔ اب جائیں اور اس چور کو ڈھونڈیں! گڈ لک!',
  },
  hi: {
    'Find the Thief': 'चोर को ढूंढो',
    'Local Play': 'स्थानीय खेल',
    'Multiplayer': 'मल्टीप्लेयर',
    'Settings': 'सेटिंग्स',
    'Update Suggests': 'सुझाव',
    'Bug Report': 'बग रिपोर्ट',
    'Tutorial': 'ट्यूटोरियल',
    'Theme': 'थीम',
    'Wooden': 'लकड़ी',
    'Modern Futuristic': 'आधुनिक भविष्य',
    'Minecraft': 'माइनक्राफ्ट',
    'GTA 5': 'जीटीए 5',
    'Classic': 'क्लासिक',
    'Paper': 'कागज़',
    'Real Life': 'वास्तविक जीवन',
    'Sound': 'ध्वनि',
    'Vibration': 'कंपन',
    'Music': 'संगीत',
    'Back': 'वापस',
    'Send': 'भेजें',
    'Enter Admin Password': 'एडमिन पासवर्ड डालें',
    'You are not admin, can’t see suggests.': 'आप एडमिन नहीं हैं, सुझाव नहीं देख सकते।',
    'No suggestions yet.': 'अभी तक कोई सुझाव नहीं है।',
    'Suggestions': 'सुझाव',
    'Write your suggestion here...': 'अपना सुझाव यहां लिखें...',
    'View Suggestions': 'सुझाव देखें',
    'Bug Reports': 'बग रिपोर्ट',
    'Describe the bug...': 'बग का वर्णन करें...',
    'Upload Screenshot (Optional)': 'स्क्रीनशॉट अपलोड करें (वैकल्पिक)',
    'No bug reports yet.': 'अभी तक कोई बग रिपोर्ट नहीं है।',
    'Enter Players': 'खिलाड़ी दर्ज करें',
    'Number of Players': 'खिलाड़ियों की संख्या',
    'Player Name': 'खिलाड़ी का नाम',
    'Role Points': 'भूमिका अंक',
    'Total Rounds': 'कुल राउंड',
    'Start Game': 'खेल शुरू करें',
    'Select Paper': 'कागज चुनें',
    'Your Role is...': 'आपकी भूमिका है...',
    'OK': 'ठीक है',
    'Reveal Roles': 'भूमिकाएं प्रकट करें',
    'All roles revealed!': 'सभी भूमिकाएं प्रकट हो गईं!',
    'Start Round': 'राउंड शुरू करें',
    'Round': 'राउंड',
    'of': 'का',
    'King': 'राजा',
    'Minister': 'मंत्री',
    'Soldier': 'सैनिक',
    'Thief': 'चोर',
    'Queen': 'रानी',
    'Prince': 'राजकुमार',
    'Chef': 'शेफ',
    'Gardener': 'माली',
    'commands': 'आदेश देता है',
    'Find the Thief!': 'चोर को ढूंढो!',
    'Guess the Thief': 'चोर का अनुमान लगाएं',
    'Correct Guess!': 'सही अनुमान!',
    'Wrong Guess!': 'गलत अनुमान!',
    'was the Thief.': 'चोर था।',
    'Next Round': 'अगला राउंड',
    'Show Results': 'परिणाम दिखाएं',
    'Game Over': 'खेल खत्म',
    'Final Scores': 'अंतिम स्कोर',
    'Restart': 'पुनः आरंभ करें',
    'Exit': 'बाहर निकलें',
    'Pause': 'रोकें',
    'Resume': 'फिर से शुरू करें',
    'Game Paused': 'खेल रुका हुआ है',
    'Points': 'अंक',
    'Lost': 'हार गए',
    'Number of AI Opponents': 'एआई विरोधियों की संख्या',
    'Your Name': 'आपका नाम',
    'Minister is thinking...': 'मंत्री सोच रहा है...',
    'Add Player': 'खिलाड़ी जोड़ें',
    'Remove': 'हटाएं',
    'Human': 'इंसान',
    'AI': 'एआई',
    'Player Names': 'खिलाड़ियों के नाम',
    'Coins': 'सिक्के',
    'Buy Hint': 'संकेत खरीदें',
    'Hint': 'संकेत',
    'is not the Thief.': 'चोर नहीं है।',
    'Not enough coins!': 'पर्याप्त सिक्के नहीं हैं!',
    'You earned': 'आपने कमाए',
    'coins!': 'सिक्के!',
    'No coins are awarded in 2-player human games.': '2 मानव खिलाड़ियों वाले खेलों में कोई सिक्के नहीं दिए जाते।',
    'Username': 'उपयोगकर्ता नाम',
    'Continue': 'जारी रखें',
    'Enter your username': 'अपना उपयोगकर्ता नाम दर्ज करें',
    'Create Game': 'खेल बनाएं',
    'Join Game': 'खेल में शामिल हों',
    'Enter Game ID': 'खेल आईडी दर्ज करें',
    'Game ID': 'खेल आईडी',
    'Copy': 'कॉपी',
    'Copied!': 'कॉपी किया गया!',
    'Waiting for players...': 'खिलाड़ियों की प्रतीक्षा है...',
    'Leave Lobby': 'लॉबी छोड़ें',
    'Players': 'खिलाड़ी',
    'Game not found.': 'खेल नहीं मिला।',
    'Lobby is full.': 'लॉबी भरी हुई है।',
    'Game has already started.': 'खेल पहले ही शुरू हो चुका है।',
    'Small Hint': 'छोटा संकेत',
    'Normal Hint': 'सामान्य संकेत',
    'Big Hint': 'बड़ा संकेत',
    'Real Answer': 'असली जवाब',
    'Reveal one innocent player.': 'एक निर्दोष खिलाड़ी को प्रकट करें।',
    'Reveal two innocent players.': 'दो निर्दोष खिलाड़ियों को प्रकट करें।',
    'Reveal three innocent players.': 'तीन निर्दोष खिलाड़ियों को प्रकट करें।',
    'Reveal the Thief!': 'चोर को प्रकट करो!',
    'is the Thief!': 'चोर है!',
    'and': 'और',
    'are not the Thief.': 'चोर नहीं हैं।',
    'Not enough players for this hint.': 'इस संकेत के लिए पर्याप्त खिलाड़ी नहीं हैं।',
    'Previous': 'पिछला',
    'Next': 'अगला',
    'Welcome to Find the Thief!': 'चोर को ढूंढो में आपका स्वागत है!',
    'The goal is simple: The Minister must find and identify the Thief to win the round.': 'लक्ष्य सरल है: मंत्री को राउंड जीतने के लिए चोर को ढूंढना और पहचानना होगा।',
    'Meet the Key Players': 'मुख्य खिलाड़ियों से मिलें',
    'King_Desc': 'शासक! उनका स्कोर सुरक्षित है।',
    'Minister_Desc': 'जासूस! उन्हें अनुमान लगाना होगा कि चोर कौन है।',
    'Soldier_Desc': 'रक्षक! उनकी एक भूमिका है लेकिन अनुमान लगाने के चरण में कार्य नहीं करते हैं।',
    'Thief_Desc': 'अपराधी! यदि मंत्री गलत अनुमान लगाता है तो वे जीत जाते हैं।',
    'A Round of Play': 'खेल का एक दौर',
    'Round_Desc': '१. सभी को एक गुप्त भूमिका मिलती है। २. राजा मंत्री को चोर को खोजने का आदेश देता है। ३. मंत्री एक अनुमान लगाता है। ४. भूमिकाएँ प्रकट की जाती हैं, और अंक दिए जाते हैं।',
    'Winning & Losing': 'जीतना और हारना',
    'Scoring_Desc': 'यदि मंत्री सही अनुमान लगाता है, तो उसे अंक मिलते हैं। यदि वे गलत हैं, तो चोर को अंक मिलते हैं, और उस दौर के लिए मंत्री का स्कोर शून्य हो जाता है! सभी दौरों के बाद सबसे अधिक अंकों वाला खिलाड़ी जीतता है।',
    "You're Ready!": 'आप तैयार हैं!',
    'Good_Luck': 'आपको बस इतना ही जानना है। अब जाओ और उस चोर को ढूंढो! शुभकामनाएँ!',
  },
  ro: {
    'Find the Thief': 'Chor ko Talash Karein',
    'Local Play': 'Local Khel',
    'Multiplayer': 'Multiplayer',
    'Settings': 'Settings',
    'Update Suggests': 'Tajaveez',
    'Bug Report': 'Bug Report',
    'Tutorial': 'Taleem',
    'Theme': 'Theme',
    'Wooden': 'Lakri',
    'Modern Futuristic': 'Jadeed Mustaqbil',
    'Minecraft': 'Minecraft',
    'GTA 5': 'GTA 5',
    'Classic': 'Classic',
    'Paper': 'Kaghazi',
    'Real Life': 'Haqeeqi Zindagi',
    'Sound': 'Awaz',
    'Vibration': 'Thartharahat',
    'Music': 'Moseeqi',
    'Back': 'Wapis',
    'Send': 'Bhejein',
    'Enter Admin Password': 'Admin Password Darj Karein',
    'You are not admin, can’t see suggests.': 'Aap admin nahi hain, tajaveez nahi dekh sakte.',
    'No suggestions yet.': 'Abhi tak koi tajaveez nahi hain.',
    'Suggestions': 'Tajaveez',
    'Write your suggestion here...': 'Apni tajweez yahan likhein...',
    'View Suggestions': 'Tajaveez Dekhein',
    'Bug Reports': 'Bug Reports',
    'Describe the bug...': 'Bug ki wazahat karein...',
    'Upload Screenshot (Optional)': 'Screenshot Upload Karein (Ikhtiyari)',
    'No bug reports yet.': 'Abhi tak koi bug report nahi hai.',
    'Enter Players': 'Khiladi dakhil karein',
    'Number of Players': 'Khiladiyon ki tadad',
    'Player Name': 'Khiladi ka Naam',
    'Role Points': 'Kirdar ke Points',
    'Total Rounds': 'Kul Rounds',
    'Start Game': 'Khel Shuru Karein',
    'Select Paper': 'Kaghaz Muntakhab Karein',
    'Your Role is...': 'Aap ka kirdar hai...',
    'OK': 'Theek hai',
    'Reveal Roles': 'Kirdar Zahir Karein',
    'All roles revealed!': 'Sab kirdar zahir ho gaye!',
    'Start Round': 'Round Shuru Karein',
    'Round': 'Round',
    'of': 'ka',
    'King': 'Badshah',
    'Minister': 'Wazir',
    'Soldier': 'Sipahi',
    'Thief': 'Chor',
    'Queen': 'Malka',
    'Prince': 'Shehzada',
    'Chef': 'Bawarchi',
    'Gardener': 'Maali',
    'commands': 'hukum deta hai',
    'Find the Thief!': 'Chor ko dhoondo!',
    'Guess the Thief': 'Chor ka andaza lagayein',
    'Correct Guess!': 'Sahi andaza!',
    'Wrong Guess!': 'Ghalat andaza!',
    'was the Thief.': 'chor tha.',
    'Next Round': 'Agla Round',
    'Show Results': 'Nataij Dikhayein',
    'Game Over': 'Khel Khatam',
    'Aakhri Scores': 'Aakhri Scores',
    'Restart': 'Dobara Shuru Karein',
    'Exit': 'Bahir Niklein',
    'Pause': 'Rokein',
    'Resume': 'Dobara Shuru',
    'Game Paused': 'Khel roka gaya',
    'Points': 'Points',
    'Haar gaye': 'Haar gaye',
    'Number of AI Opponents': 'AI Mukhalfin ki Tadad',
    'Aapka Naam': 'Aapka Naam',
    'Minister is thinking...': 'Wazir soch raha hai...',
    'Add Player': 'Khiladi Shamil Karein',
    'Remove': 'Hatayein',
    'Human': 'Insan',
    'AI': 'AI',
    'Player Names': 'Khiladiyon ke Naam',
    'Coins': 'Sikkay',
    'Buy Hint': 'Ishara Khareedein',
    'Hint': 'Ishara',
    'is not the Thief.': 'chor nahi hai.',
    'Not enough coins!': 'Kafi sikkay nahi hain!',
    'You earned': 'Aap ne kamaye',
    'coins!': 'sikkay!',
    'No coins are awarded in 2-player human games.': '2 insani khiladiyon walay khelon mein koi sikkay nahi diye jatay.',
    'Username': 'Username',
    'Continue': 'Jari Rakhein',
    'Enter your username': 'Apna username darj karein',
    'Create Game': 'Game Banayein',
    'Join Game': 'Game Join Karein',
    'Enter Game ID': 'Game ID Darj Karein',
    'Game ID': 'Game ID',
    'Copy': 'Copy',
    'Copied!': 'Copy ho gaya!',
    'Waiting for players...': 'Khiladiyon ka intezar hai...',
    'Leave Lobby': 'Lobby Chorein',
    'Players': 'Khiladi',
    'Game not found.': 'Game nahi mila.',
    'Lobby is full.': 'Lobby bhari hui hai.',
    'Game has already started.': 'Khel pehle hi shuru ho chuka hai.',
    'Small Hint': 'Chota Ishara',
    'Normal Hint': 'Normal Ishara',
    'Big Hint': 'Bara Ishara',
    'Real Answer': 'Asli Jawab',
    'Reveal one innocent player.': 'Aik masoom khiladi ko zahir karein.',
    'Reveal two innocent players.': 'Do masoom khiladiyon ko zahir karein.',
    'Reveal three innocent players.': 'Teen masoom khiladiyon ko zahir karein.',
    'Reveal the Thief!': 'Chor ko zahir karo!',
    'is the Thief!': 'chor hai!',
    'and': 'aur',
    'are not the Thief.': 'chor nahi hain.',
    'Not enough players for this hint.': 'Is ishary ke liye kafi khiladi nahi hain.',
    'Previous': 'Pichla',
    'Next': 'Agla',
    'Welcome to Find the Thief!': 'Chor ko Talash Karein mein Khush Amdeed!',
    'The goal is simple: The Minister must find and identify the Thief to win the round.': 'Maqsad asan hai: Wazir ko round jeetne ke liye Chor ko dhoondna aur shanakht karna hoga.',
    'Meet the Key Players': 'Ahem Khiladiyon se Milein',
    'King_Desc': 'Hukmaran! Unka score mehfooz hai.',
    'Minister_Desc': 'Jasoos! Unhein andaza lagana hoga ke Chor kon hai.',
    'Soldier_Desc': 'Muhafiz! Unka ek kirdar hai lekin andaza lagane ke marhalay mein koi amal nahi.',
    'Thief_Desc': 'Mujrim! Agar Wazir ghalat andaza lagata hai to woh jeet jatay hain.',
    'A Round of Play': 'Khel ka ek Round',
    'Round_Desc': '1. Har kisi ko ek khufia kirdar milta hai. 2. Badshah Wazir ko Chor dhoondne ka hukum deta hai. 3. Wazir ek andaza lagata hai. 4. Kirdar zahir kiye jatay hain, aur points diye jatay hain.',
    'Winning & Losing': 'Jeetna aur Haarna',
    'Scoring_Desc': 'Agar Wazir sahi andaza lagata hai, to usay points miltay hain. Agar woh ghalat hai, to Chor ko points miltay hain, aur Wazir ka us round ka score zero hojata hai! Tamam rounds ke baad sab se ziyada points wala khiladi jeetta hai.',
    "You're Ready!": 'Aap Tayyar Hain!',
    'Good_Luck': 'Aap ko bas itna hi jan\'nay ki zaroorat hai. Ab jayein aur us chor ko dhoondein! Good luck!',
  },
};